### ISSUE TITLE
Incorrect channel in feed/listener message

### ISSUE THREAD

**Issue by jrday** [atomist/sdm-local#108]
When creating a new spring project, the first message in the feed/listener log shows as coming from an incorrect channel (which happens to be the last channel there was activity in on this sdm).

![channel-conflict](https://user-images.githubusercontent.com/774714/44063191-7d72950a-9f14-11e8-9838-4658ba7be342.png)

**Comment by johnsonr** [comment]
This is actually expected behavior.

1 - the first (cloning) message comes from the "current" channel, which is inferred from the directory location of the prompt. This would be the same in the bot

2- The second message is explicitly sent to general as the result of a listener. It's part of `sample-sdm` not standard behavior

3- Following messages go to the new channel.
