### ISSUE TITLE
Spring goals block after Build after break and fix to new project

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#95]
@jrday can you please document the steps to reproduce this and then assign to me

**Comment by jrday** [comment]
1. `npm install -g @atomist/cli`
2. `atomist new sdm` - choose spring sdm
3. `cd ${new_sdm_dir}; atomist start --local`
4. `atomist create spring` - create new spring boot project, sdm goals all successfully ran

<img width="1003" alt="success" src="https://user-images.githubusercontent.com/774714/43985708-7df1588e-9cbe-11e8-9e57-4b0a4e847925.png">

5. Edit ${project_name}Controller.java file and introduce a syntax error (I changed the first `import` to `iimport`) and `git commit -a -m 'typo'` The sdm goals ran, and failed at the build step.

<img width="1002" alt="typo" src="https://user-images.githubusercontent.com/774714/43985717-8864f816-9cbe-11e8-9b84-1129a719a0e4.png">

6. Fixed the syntax error and `git commit -a -m 'typo-fix'`. The sdm goals stop after build (successful build).

<img width="976" alt="typo-fix" src="https://user-images.githubusercontent.com/774714/43985721-8f5690a8-9cbe-11e8-9ecb-c59a00438dd8.png">

7. Subsequent commit also did not progress beyond build goal

<img width="990" alt="post-typo-fix" src="https://user-images.githubusercontent.com/774714/43985770-ec410f8c-9cbe-11e8-9f51-d6ee0ca7990b.png">

**Comment by jrday** [comment]
I’m able to reproduce and avoid the issue manually. It appears related to the fact that `package.json` name gets transformed to the new sdm project name, but `package-lock.json` name remains unchanged as `@atomist/sample-sdm, "version": "0.5.1"`
However, as soon as I fail the maven build step, the `package-lock.json` file gets rewritten with the sdm project name instead of `@atomist/sample-sdm`. It seems like it’s being run as `@atomist/sample-sdm` initially, because of the `package-lock.json` file, but then when the maven build fails, something is updating `package-lock.json`.

Haven't been able to dig into it deeper to see what's really causing the change.

**Comment by cdupuis** [comment]
With my work yesterday I can’t reproduce this any longer.
